// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_data.proto

package ruifusoft.protocol;

public final class UserData {
  private UserData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 user_id = 1;
    boolean hasUserId();
    int getUserId();
    
    // required string name = 2;
    boolean hasName();
    String getName();
    
    // required string passwd = 3;
    boolean hasPasswd();
    String getPasswd();
    
    // optional string mobile = 4;
    boolean hasMobile();
    String getMobile();
    
    // optional string email = 5;
    boolean hasEmail();
    String getEmail();
    
    // optional int32 bind_type = 6;
    boolean hasBindType();
    int getBindType();
    
    // optional bool active = 7;
    boolean hasActive();
    boolean getActive();
    
    // optional int64 create_time = 8;
    boolean hasCreateTime();
    long getCreateTime();
    
    // optional int64 last_update_time = 9;
    boolean hasLastUpdateTime();
    long getLastUpdateTime();
  }
  public static final class User extends
      com.google.protobuf.GeneratedMessage
      implements UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(Builder builder) {
      super(builder);
    }
    private User(boolean noInit) {}
    
    private static final User defaultInstance;
    public static User getDefaultInstance() {
      return defaultInstance;
    }
    
    public User getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserData.internal_static_ruifusoft_protocol_User_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserData.internal_static_ruifusoft_protocol_User_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 user_id = 1;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getUserId() {
      return userId_;
    }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string passwd = 3;
    public static final int PASSWD_FIELD_NUMBER = 3;
    private Object passwd_;
    public boolean hasPasswd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getPasswd() {
      Object ref = passwd_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          passwd_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPasswdBytes() {
      Object ref = passwd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        passwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string mobile = 4;
    public static final int MOBILE_FIELD_NUMBER = 4;
    private Object mobile_;
    public boolean hasMobile() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getMobile() {
      Object ref = mobile_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          mobile_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMobileBytes() {
      Object ref = mobile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string email = 5;
    public static final int EMAIL_FIELD_NUMBER = 5;
    private Object email_;
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getEmail() {
      Object ref = email_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          email_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEmailBytes() {
      Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 bind_type = 6;
    public static final int BIND_TYPE_FIELD_NUMBER = 6;
    private int bindType_;
    public boolean hasBindType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getBindType() {
      return bindType_;
    }
    
    // optional bool active = 7;
    public static final int ACTIVE_FIELD_NUMBER = 7;
    private boolean active_;
    public boolean hasActive() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public boolean getActive() {
      return active_;
    }
    
    // optional int64 create_time = 8;
    public static final int CREATE_TIME_FIELD_NUMBER = 8;
    private long createTime_;
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public long getCreateTime() {
      return createTime_;
    }
    
    // optional int64 last_update_time = 9;
    public static final int LAST_UPDATE_TIME_FIELD_NUMBER = 9;
    private long lastUpdateTime_;
    public boolean hasLastUpdateTime() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public long getLastUpdateTime() {
      return lastUpdateTime_;
    }
    
    private void initFields() {
      userId_ = 0;
      name_ = "";
      passwd_ = "";
      mobile_ = "";
      email_ = "";
      bindType_ = 0;
      active_ = false;
      createTime_ = 0L;
      lastUpdateTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPasswd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPasswdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getMobileBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getEmailBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, bindType_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, active_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, createTime_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt64(9, lastUpdateTime_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPasswdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getMobileBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getEmailBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, bindType_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, active_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, createTime_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, lastUpdateTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserData.internal_static_ruifusoft_protocol_User_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserData.internal_static_ruifusoft_protocol_User_fieldAccessorTable;
      }
      
      // Construct using ruifusoft.protocol.UserData.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        passwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        mobile_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        bindType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        active_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        createTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        lastUpdateTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return User.getDescriptor();
      }
      
      public User getDefaultInstanceForType() {
        return User.getDefaultInstance();
      }
      
      public User build() {
        User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private User buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public User buildPartial() {
        User result = new User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.passwd_ = passwd_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mobile_ = mobile_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.bindType_ = bindType_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.active_ = active_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.createTime_ = createTime_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.lastUpdateTime_ = lastUpdateTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof User) {
          return mergeFrom((User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(User other) {
        if (other == User.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasPasswd()) {
          setPasswd(other.getPasswd());
        }
        if (other.hasMobile()) {
          setMobile(other.getMobile());
        }
        if (other.hasEmail()) {
          setEmail(other.getEmail());
        }
        if (other.hasBindType()) {
          setBindType(other.getBindType());
        }
        if (other.hasActive()) {
          setActive(other.getActive());
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasLastUpdateTime()) {
          setLastUpdateTime(other.getLastUpdateTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasPasswd()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              passwd_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              mobile_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              email_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              bindType_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              active_ = input.readBool();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              createTime_ = input.readInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              lastUpdateTime_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 user_id = 1;
      private int userId_ ;
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getUserId() {
        return userId_;
      }
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }
      
      // required string name = 2;
      private Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // required string passwd = 3;
      private Object passwd_ = "";
      public boolean hasPasswd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPasswd() {
        Object ref = passwd_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          passwd_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPasswd(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        passwd_ = value;
        onChanged();
        return this;
      }
      public Builder clearPasswd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        passwd_ = getDefaultInstance().getPasswd();
        onChanged();
        return this;
      }
      void setPasswd(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        passwd_ = value;
        onChanged();
      }
      
      // optional string mobile = 4;
      private Object mobile_ = "";
      public boolean hasMobile() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getMobile() {
        Object ref = mobile_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          mobile_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMobile(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        mobile_ = value;
        onChanged();
        return this;
      }
      public Builder clearMobile() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mobile_ = getDefaultInstance().getMobile();
        onChanged();
        return this;
      }
      void setMobile(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        mobile_ = value;
        onChanged();
      }
      
      // optional string email = 5;
      private Object email_ = "";
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getEmail() {
        Object ref = email_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEmail(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        email_ = value;
        onChanged();
        return this;
      }
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000010);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      void setEmail(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        email_ = value;
        onChanged();
      }
      
      // optional int32 bind_type = 6;
      private int bindType_ ;
      public boolean hasBindType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getBindType() {
        return bindType_;
      }
      public Builder setBindType(int value) {
        bitField0_ |= 0x00000020;
        bindType_ = value;
        onChanged();
        return this;
      }
      public Builder clearBindType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        bindType_ = 0;
        onChanged();
        return this;
      }
      
      // optional bool active = 7;
      private boolean active_ ;
      public boolean hasActive() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public boolean getActive() {
        return active_;
      }
      public Builder setActive(boolean value) {
        bitField0_ |= 0x00000040;
        active_ = value;
        onChanged();
        return this;
      }
      public Builder clearActive() {
        bitField0_ = (bitField0_ & ~0x00000040);
        active_ = false;
        onChanged();
        return this;
      }
      
      // optional int64 create_time = 8;
      private long createTime_ ;
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public long getCreateTime() {
        return createTime_;
      }
      public Builder setCreateTime(long value) {
        bitField0_ |= 0x00000080;
        createTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000080);
        createTime_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 last_update_time = 9;
      private long lastUpdateTime_ ;
      public boolean hasLastUpdateTime() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public long getLastUpdateTime() {
        return lastUpdateTime_;
      }
      public Builder setLastUpdateTime(long value) {
        bitField0_ |= 0x00000100;
        lastUpdateTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastUpdateTime() {
        bitField0_ = (bitField0_ & ~0x00000100);
        lastUpdateTime_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ruifusoft.protocol.User)
    }
    
    static {
      defaultInstance = new User(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ruifusoft.protocol.User)
  }
  
  public interface UserProfileOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 user_id = 1;
    boolean hasUserId();
    int getUserId();
    
    // optional int32 sex = 2;
    boolean hasSex();
    int getSex();
    
    // optional int64 birthday = 3;
    boolean hasBirthday();
    long getBirthday();
    
    // optional string id_card = 4;
    boolean hasIdCard();
    String getIdCard();
    
    // optional string passport_no = 5;
    boolean hasPassportNo();
    String getPassportNo();
    
    // optional string avatar_file_path = 6;
    boolean hasAvatarFilePath();
    String getAvatarFilePath();
    
    // optional string qq = 7;
    boolean hasQq();
    String getQq();
    
    // optional string qq_extra = 8;
    boolean hasQqExtra();
    String getQqExtra();
    
    // optional string weixin = 9;
    boolean hasWeixin();
    String getWeixin();
    
    // optional string weixin_extra = 10;
    boolean hasWeixinExtra();
    String getWeixinExtra();
    
    // optional string weibo = 11;
    boolean hasWeibo();
    String getWeibo();
    
    // optional string weibo_extra = 12;
    boolean hasWeiboExtra();
    String getWeiboExtra();
    
    // optional int64 create_time = 13;
    boolean hasCreateTime();
    long getCreateTime();
    
    // optional int64 last_update_time = 14;
    boolean hasLastUpdateTime();
    long getLastUpdateTime();
  }
  public static final class UserProfile extends
      com.google.protobuf.GeneratedMessage
      implements UserProfileOrBuilder {
    // Use UserProfile.newBuilder() to construct.
    private UserProfile(Builder builder) {
      super(builder);
    }
    private UserProfile(boolean noInit) {}
    
    private static final UserProfile defaultInstance;
    public static UserProfile getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserProfile getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserData.internal_static_ruifusoft_protocol_UserProfile_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserData.internal_static_ruifusoft_protocol_UserProfile_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 user_id = 1;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getUserId() {
      return userId_;
    }
    
    // optional int32 sex = 2;
    public static final int SEX_FIELD_NUMBER = 2;
    private int sex_;
    public boolean hasSex() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getSex() {
      return sex_;
    }
    
    // optional int64 birthday = 3;
    public static final int BIRTHDAY_FIELD_NUMBER = 3;
    private long birthday_;
    public boolean hasBirthday() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getBirthday() {
      return birthday_;
    }
    
    // optional string id_card = 4;
    public static final int ID_CARD_FIELD_NUMBER = 4;
    private Object idCard_;
    public boolean hasIdCard() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getIdCard() {
      Object ref = idCard_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          idCard_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdCardBytes() {
      Object ref = idCard_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        idCard_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string passport_no = 5;
    public static final int PASSPORT_NO_FIELD_NUMBER = 5;
    private Object passportNo_;
    public boolean hasPassportNo() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getPassportNo() {
      Object ref = passportNo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          passportNo_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPassportNoBytes() {
      Object ref = passportNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        passportNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string avatar_file_path = 6;
    public static final int AVATAR_FILE_PATH_FIELD_NUMBER = 6;
    private Object avatarFilePath_;
    public boolean hasAvatarFilePath() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getAvatarFilePath() {
      Object ref = avatarFilePath_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          avatarFilePath_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAvatarFilePathBytes() {
      Object ref = avatarFilePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        avatarFilePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string qq = 7;
    public static final int QQ_FIELD_NUMBER = 7;
    private Object qq_;
    public boolean hasQq() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getQq() {
      Object ref = qq_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          qq_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getQqBytes() {
      Object ref = qq_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        qq_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string qq_extra = 8;
    public static final int QQ_EXTRA_FIELD_NUMBER = 8;
    private Object qqExtra_;
    public boolean hasQqExtra() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getQqExtra() {
      Object ref = qqExtra_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          qqExtra_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getQqExtraBytes() {
      Object ref = qqExtra_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        qqExtra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string weixin = 9;
    public static final int WEIXIN_FIELD_NUMBER = 9;
    private Object weixin_;
    public boolean hasWeixin() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getWeixin() {
      Object ref = weixin_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          weixin_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getWeixinBytes() {
      Object ref = weixin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        weixin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string weixin_extra = 10;
    public static final int WEIXIN_EXTRA_FIELD_NUMBER = 10;
    private Object weixinExtra_;
    public boolean hasWeixinExtra() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getWeixinExtra() {
      Object ref = weixinExtra_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          weixinExtra_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getWeixinExtraBytes() {
      Object ref = weixinExtra_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        weixinExtra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string weibo = 11;
    public static final int WEIBO_FIELD_NUMBER = 11;
    private Object weibo_;
    public boolean hasWeibo() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public String getWeibo() {
      Object ref = weibo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          weibo_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getWeiboBytes() {
      Object ref = weibo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        weibo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string weibo_extra = 12;
    public static final int WEIBO_EXTRA_FIELD_NUMBER = 12;
    private Object weiboExtra_;
    public boolean hasWeiboExtra() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public String getWeiboExtra() {
      Object ref = weiboExtra_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          weiboExtra_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getWeiboExtraBytes() {
      Object ref = weiboExtra_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        weiboExtra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 create_time = 13;
    public static final int CREATE_TIME_FIELD_NUMBER = 13;
    private long createTime_;
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public long getCreateTime() {
      return createTime_;
    }
    
    // optional int64 last_update_time = 14;
    public static final int LAST_UPDATE_TIME_FIELD_NUMBER = 14;
    private long lastUpdateTime_;
    public boolean hasLastUpdateTime() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public long getLastUpdateTime() {
      return lastUpdateTime_;
    }
    
    private void initFields() {
      userId_ = 0;
      sex_ = 0;
      birthday_ = 0L;
      idCard_ = "";
      passportNo_ = "";
      avatarFilePath_ = "";
      qq_ = "";
      qqExtra_ = "";
      weixin_ = "";
      weixinExtra_ = "";
      weibo_ = "";
      weiboExtra_ = "";
      createTime_ = 0L;
      lastUpdateTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, sex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, birthday_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getIdCardBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getPassportNoBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getAvatarFilePathBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getQqBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getQqExtraBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getWeixinBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getWeixinExtraBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getWeiboBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getWeiboExtraBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt64(13, createTime_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt64(14, lastUpdateTime_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, birthday_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getIdCardBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getPassportNoBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getAvatarFilePathBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getQqBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getQqExtraBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getWeixinBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getWeixinExtraBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getWeiboBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getWeiboExtraBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(13, createTime_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(14, lastUpdateTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static UserProfile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static UserProfile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static UserProfile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static UserProfile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static UserProfile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static UserProfile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static UserProfile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static UserProfile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static UserProfile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static UserProfile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(UserProfile prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements UserProfileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserData.internal_static_ruifusoft_protocol_UserProfile_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserData.internal_static_ruifusoft_protocol_UserProfile_fieldAccessorTable;
      }
      
      // Construct using ruifusoft.protocol.UserData.UserProfile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        birthday_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        idCard_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        passportNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        avatarFilePath_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        qq_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        qqExtra_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        weixin_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        weixinExtra_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        weibo_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        weiboExtra_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        createTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00001000);
        lastUpdateTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00002000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserProfile.getDescriptor();
      }
      
      public UserProfile getDefaultInstanceForType() {
        return UserProfile.getDefaultInstance();
      }
      
      public UserProfile build() {
        UserProfile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private UserProfile buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        UserProfile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public UserProfile buildPartial() {
        UserProfile result = new UserProfile(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.birthday_ = birthday_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.idCard_ = idCard_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.passportNo_ = passportNo_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.avatarFilePath_ = avatarFilePath_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.qq_ = qq_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.qqExtra_ = qqExtra_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.weixin_ = weixin_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.weixinExtra_ = weixinExtra_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.weibo_ = weibo_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.weiboExtra_ = weiboExtra_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.createTime_ = createTime_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.lastUpdateTime_ = lastUpdateTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserProfile) {
          return mergeFrom((UserProfile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(UserProfile other) {
        if (other == UserProfile.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        if (other.hasBirthday()) {
          setBirthday(other.getBirthday());
        }
        if (other.hasIdCard()) {
          setIdCard(other.getIdCard());
        }
        if (other.hasPassportNo()) {
          setPassportNo(other.getPassportNo());
        }
        if (other.hasAvatarFilePath()) {
          setAvatarFilePath(other.getAvatarFilePath());
        }
        if (other.hasQq()) {
          setQq(other.getQq());
        }
        if (other.hasQqExtra()) {
          setQqExtra(other.getQqExtra());
        }
        if (other.hasWeixin()) {
          setWeixin(other.getWeixin());
        }
        if (other.hasWeixinExtra()) {
          setWeixinExtra(other.getWeixinExtra());
        }
        if (other.hasWeibo()) {
          setWeibo(other.getWeibo());
        }
        if (other.hasWeiboExtra()) {
          setWeiboExtra(other.getWeiboExtra());
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasLastUpdateTime()) {
          setLastUpdateTime(other.getLastUpdateTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sex_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              birthday_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              idCard_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              passportNo_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              avatarFilePath_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              qq_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              qqExtra_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              weixin_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              weixinExtra_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              weibo_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              weiboExtra_ = input.readBytes();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              createTime_ = input.readInt64();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              lastUpdateTime_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 user_id = 1;
      private int userId_ ;
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getUserId() {
        return userId_;
      }
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 sex = 2;
      private int sex_ ;
      public boolean hasSex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getSex() {
        return sex_;
      }
      public Builder setSex(int value) {
        bitField0_ |= 0x00000002;
        sex_ = value;
        onChanged();
        return this;
      }
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sex_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 birthday = 3;
      private long birthday_ ;
      public boolean hasBirthday() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getBirthday() {
        return birthday_;
      }
      public Builder setBirthday(long value) {
        bitField0_ |= 0x00000004;
        birthday_ = value;
        onChanged();
        return this;
      }
      public Builder clearBirthday() {
        bitField0_ = (bitField0_ & ~0x00000004);
        birthday_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string id_card = 4;
      private Object idCard_ = "";
      public boolean hasIdCard() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getIdCard() {
        Object ref = idCard_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          idCard_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIdCard(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        idCard_ = value;
        onChanged();
        return this;
      }
      public Builder clearIdCard() {
        bitField0_ = (bitField0_ & ~0x00000008);
        idCard_ = getDefaultInstance().getIdCard();
        onChanged();
        return this;
      }
      void setIdCard(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        idCard_ = value;
        onChanged();
      }
      
      // optional string passport_no = 5;
      private Object passportNo_ = "";
      public boolean hasPassportNo() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getPassportNo() {
        Object ref = passportNo_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          passportNo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPassportNo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        passportNo_ = value;
        onChanged();
        return this;
      }
      public Builder clearPassportNo() {
        bitField0_ = (bitField0_ & ~0x00000010);
        passportNo_ = getDefaultInstance().getPassportNo();
        onChanged();
        return this;
      }
      void setPassportNo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        passportNo_ = value;
        onChanged();
      }
      
      // optional string avatar_file_path = 6;
      private Object avatarFilePath_ = "";
      public boolean hasAvatarFilePath() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getAvatarFilePath() {
        Object ref = avatarFilePath_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          avatarFilePath_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAvatarFilePath(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        avatarFilePath_ = value;
        onChanged();
        return this;
      }
      public Builder clearAvatarFilePath() {
        bitField0_ = (bitField0_ & ~0x00000020);
        avatarFilePath_ = getDefaultInstance().getAvatarFilePath();
        onChanged();
        return this;
      }
      void setAvatarFilePath(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        avatarFilePath_ = value;
        onChanged();
      }
      
      // optional string qq = 7;
      private Object qq_ = "";
      public boolean hasQq() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getQq() {
        Object ref = qq_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          qq_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setQq(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        qq_ = value;
        onChanged();
        return this;
      }
      public Builder clearQq() {
        bitField0_ = (bitField0_ & ~0x00000040);
        qq_ = getDefaultInstance().getQq();
        onChanged();
        return this;
      }
      void setQq(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        qq_ = value;
        onChanged();
      }
      
      // optional string qq_extra = 8;
      private Object qqExtra_ = "";
      public boolean hasQqExtra() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getQqExtra() {
        Object ref = qqExtra_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          qqExtra_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setQqExtra(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        qqExtra_ = value;
        onChanged();
        return this;
      }
      public Builder clearQqExtra() {
        bitField0_ = (bitField0_ & ~0x00000080);
        qqExtra_ = getDefaultInstance().getQqExtra();
        onChanged();
        return this;
      }
      void setQqExtra(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        qqExtra_ = value;
        onChanged();
      }
      
      // optional string weixin = 9;
      private Object weixin_ = "";
      public boolean hasWeixin() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getWeixin() {
        Object ref = weixin_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          weixin_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setWeixin(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        weixin_ = value;
        onChanged();
        return this;
      }
      public Builder clearWeixin() {
        bitField0_ = (bitField0_ & ~0x00000100);
        weixin_ = getDefaultInstance().getWeixin();
        onChanged();
        return this;
      }
      void setWeixin(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        weixin_ = value;
        onChanged();
      }
      
      // optional string weixin_extra = 10;
      private Object weixinExtra_ = "";
      public boolean hasWeixinExtra() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getWeixinExtra() {
        Object ref = weixinExtra_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          weixinExtra_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setWeixinExtra(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        weixinExtra_ = value;
        onChanged();
        return this;
      }
      public Builder clearWeixinExtra() {
        bitField0_ = (bitField0_ & ~0x00000200);
        weixinExtra_ = getDefaultInstance().getWeixinExtra();
        onChanged();
        return this;
      }
      void setWeixinExtra(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        weixinExtra_ = value;
        onChanged();
      }
      
      // optional string weibo = 11;
      private Object weibo_ = "";
      public boolean hasWeibo() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public String getWeibo() {
        Object ref = weibo_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          weibo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setWeibo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        weibo_ = value;
        onChanged();
        return this;
      }
      public Builder clearWeibo() {
        bitField0_ = (bitField0_ & ~0x00000400);
        weibo_ = getDefaultInstance().getWeibo();
        onChanged();
        return this;
      }
      void setWeibo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000400;
        weibo_ = value;
        onChanged();
      }
      
      // optional string weibo_extra = 12;
      private Object weiboExtra_ = "";
      public boolean hasWeiboExtra() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public String getWeiboExtra() {
        Object ref = weiboExtra_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          weiboExtra_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setWeiboExtra(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        weiboExtra_ = value;
        onChanged();
        return this;
      }
      public Builder clearWeiboExtra() {
        bitField0_ = (bitField0_ & ~0x00000800);
        weiboExtra_ = getDefaultInstance().getWeiboExtra();
        onChanged();
        return this;
      }
      void setWeiboExtra(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000800;
        weiboExtra_ = value;
        onChanged();
      }
      
      // optional int64 create_time = 13;
      private long createTime_ ;
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public long getCreateTime() {
        return createTime_;
      }
      public Builder setCreateTime(long value) {
        bitField0_ |= 0x00001000;
        createTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00001000);
        createTime_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 last_update_time = 14;
      private long lastUpdateTime_ ;
      public boolean hasLastUpdateTime() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public long getLastUpdateTime() {
        return lastUpdateTime_;
      }
      public Builder setLastUpdateTime(long value) {
        bitField0_ |= 0x00002000;
        lastUpdateTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastUpdateTime() {
        bitField0_ = (bitField0_ & ~0x00002000);
        lastUpdateTime_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ruifusoft.protocol.UserProfile)
    }
    
    static {
      defaultInstance = new UserProfile(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ruifusoft.protocol.UserProfile)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ruifusoft_protocol_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ruifusoft_protocol_User_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ruifusoft_protocol_UserProfile_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ruifusoft_protocol_UserProfile_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017user_data.proto\022\022ruifusoft.protocol\"\246\001" +
      "\n\004User\022\017\n\007user_id\030\001 \001(\005\022\014\n\004name\030\002 \002(\t\022\016\n" +
      "\006passwd\030\003 \002(\t\022\016\n\006mobile\030\004 \001(\t\022\r\n\005email\030\005" +
      " \001(\t\022\021\n\tbind_type\030\006 \001(\005\022\016\n\006active\030\007 \001(\010\022" +
      "\023\n\013create_time\030\010 \001(\003\022\030\n\020last_update_time" +
      "\030\t \001(\003\"\224\002\n\013UserProfile\022\017\n\007user_id\030\001 \002(\005\022" +
      "\013\n\003sex\030\002 \001(\005\022\020\n\010birthday\030\003 \001(\003\022\017\n\007id_car" +
      "d\030\004 \001(\t\022\023\n\013passport_no\030\005 \001(\t\022\030\n\020avatar_f" +
      "ile_path\030\006 \001(\t\022\n\n\002qq\030\007 \001(\t\022\020\n\010qq_extra\030\010" +
      " \001(\t\022\016\n\006weixin\030\t \001(\t\022\024\n\014weixin_extra\030\n \001",
      "(\t\022\r\n\005weibo\030\013 \001(\t\022\023\n\013weibo_extra\030\014 \001(\t\022\023" +
      "\n\013create_time\030\r \001(\003\022\030\n\020last_update_time\030" +
      "\016 \001(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ruifusoft_protocol_User_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ruifusoft_protocol_User_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ruifusoft_protocol_User_descriptor,
              new String[] { "UserId", "Name", "Passwd", "Mobile", "Email", "BindType", "Active", "CreateTime", "LastUpdateTime", },
              User.class,
              User.Builder.class);
          internal_static_ruifusoft_protocol_UserProfile_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ruifusoft_protocol_UserProfile_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ruifusoft_protocol_UserProfile_descriptor,
              new String[] { "UserId", "Sex", "Birthday", "IdCard", "PassportNo", "AvatarFilePath", "Qq", "QqExtra", "Weixin", "WeixinExtra", "Weibo", "WeiboExtra", "CreateTime", "LastUpdateTime", },
              UserProfile.class,
              UserProfile.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
